# Generated by Django 4.2.3 on 2023-10-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_items_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='bid',
            field=models.IntegerField(default=0),
        ),
    ]
