# Generated by Django 4.2.3 on 2023-10-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_items_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='bid',
            field=models.IntegerField(default=5000),
        ),
    ]
