# Generated by Django 4.2.3 on 2023-10-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_bids_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
