# Generated by Django 4.2.3 on 2023-10-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_items_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='item',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
